version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    depends_on:
      - postgres
      - redis
    networks:
      - later-nw

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - later-nw

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - later-nw

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - later-nw

volumes:
  fastapi-data:
  postgres-data:
  redis-data:

networks:
  later-nw:
