#!/bin/sh -e
set -e
APP_NAME=$(basename $(pwd))


# verify that conda environment is currently activated and its name is $(APP_NAME)-env
if [[ ! "$VIRTUAL_ENV" == "$(APP_NAME)-env" ]]; then
    echo "Conda environment is not activated. Please run 'conda activate $(APP_NAME)-env' first."
    exit 1
fi

# verify that the current working directory is the root of the project: src/__init__.py is present
if [[ ! -f "src/__init__.py" ]]; then
    echo "strt: This script must be run from the root of the project."
    exit 1
fi

PYLINT_FAILURE_THRESHOLD=9.0

echo "====== Linting ======"

# append current directory to PYTHONPATH
export PYTHONPATH=$PYTHONPATH:$(pwd)/src

# run pylint
echo "Running pylint..."
poetry run pylint src --fail-under=$PYLINT_FAILURE_THRESHOLD --rcfile=.pylintrc
echo "Pylint OK"
echo
